import type { ConfigField, ProductSchema } from "./schema-types";

export type GenerateResult = {
  config: string;
  env: string;
  cli: string;
  markdown: string;
  filename: string;
  mime: string;
};

type Values = Record<string, unknown>;

function asStringList(v: unknown): string[] {
  if (Array.isArray(v)) return v.map(String).map((s) => s.trim()).filter(Boolean);
  if (typeof v === "string")
    return v
      .split(",")
      .map((s) => s.trim())
      .filter(Boolean);
  return [];
}

function escapeTomlString(s: string): string {
  if (s.includes("\n")) {
    return `"""\n${s.replaceAll("\\", "\\\\").replaceAll('"""', '\\"""')}\n"""`;
  }
  return JSON.stringify(s);
}

function formatTomlValue(field: ConfigField, value: unknown): string | null {
  if (value == null || value === "") return null;
  if (field.type === "boolean") return value ? "true" : "false";
  if (field.type === "number") {
    if (typeof value === "number") return Number.isInteger(value) ? String(value) : String(value);
    const n = Number(value);
    if (Number.isNaN(n)) return null;
    return String(n);
  }
  if (field.type === "string-list") {
    const list = asStringList(value);
    if (!list.length) return null;
    return `[${list.map((s) => JSON.stringify(s)).join(", ")}]`;
  }
  return escapeTomlString(String(value));
}

function setNested(root: Record<string, unknown>, path: string, value: unknown) {
  const parts = path.split(".");
  let cur: Record<string, unknown> = root;
  for (let i = 0; i < parts.length - 1; i++) {
    const p = parts[i]!;
    if (!cur[p] || typeof cur[p] !== "object") cur[p] = {};
    cur = cur[p] as Record<string, unknown>;
  }
  cur[parts[parts.length - 1]!] = value;
}

function generateJson(schema: ProductSchema, enabled: Set<string>, values: Values): string {
  const root: Record<string, unknown> = {
    $schema: "https://opencode.ai/config.json",
    _comment: "OpenCode Titanium — generated by Agent Config Builders",
  };
  for (const f of schema.fields) {
    if (!enabled.has(f.id) || values[f.id] == null || values[f.id] === "") continue;
    let v: unknown = values[f.id];
    if (f.type === "string-list") v = asStringList(v);
    if (f.id === "autoupdate") {
      if (v === "true") v = true;
      else if (v === "false") v = false;
    }
    setNested(root, f.path, v);
  }
  if (enabled.has("default_agent")) {
    root.agent = {
      build: { description: "Titanium build", prompt: "Ship working code." },
      plan: { description: "Plan", prompt: "Plan first." },
      scout: { description: "Scout", prompt: "Research." },
    };
  }
  return JSON.stringify(root, null, 2) + "\n";
}

function generateToml(schema: ProductSchema, enabled: Set<string>, values: Values): string {
  const product = schema.product || "";
  const topLines: string[] = [];
  const sections: Record<string, string[]> = {};

  for (const f of schema.fields) {
    if (!enabled.has(f.id) || values[f.id] == null || values[f.id] === "") continue;
    // marketplace sources handled as tables later
    if (f.id.startsWith("marketplace.source.")) continue;
    const formatted = formatTomlValue(f, values[f.id]);
    if (!formatted) continue;

    if (f.section) {
      const key = f.path.split(".").pop()!;
      (sections[f.section] ||= []).push(`${key} = ${formatted}`);
    } else if (f.id.startsWith("provider.") && f.id !== "provider.id") {
      const pid = String(values["provider.id"] || "custom");
      const key = f.id.replace("provider.", "");
      (sections[`model_providers.${pid}`] ||= []).push(`${key} = ${formatted}`);
    } else if (f.id.startsWith("model.custom.") && f.id !== "model.custom.id") {
      const mid = String(values["model.custom.id"] || "custom");
      const key = f.id.replace("model.custom.", "");
      (sections[`model."${mid}"`] ||= []).push(`${key} = ${formatted}`);
    } else if (f.id.startsWith("mcp.") && f.id !== "mcp.id") {
      const mid = String(values["mcp.id"] || "filesystem");
      const map: Record<string, string> = {
        "mcp.enabled": "enabled",
        "mcp.command": "command",
        "mcp.args": "args",
        "mcp.startup_timeout_sec": "startup_timeout_sec",
        "mcp.tool_timeout_sec": "tool_timeout_sec",
      };
      const key = map[f.id] || f.id.replace("mcp.", "");
      (sections[`mcp_servers.${mid}`] ||= []).push(`${key} = ${formatted}`);
    } else if (f.path.includes(".")) {
      const parts = f.path.split(".");
      const key = parts.pop()!;
      const sec = parts.join(".");
      // special: permissions.permission_mode stays in permissions; remember_tool_approvals → ui
      if (f.id === "permissions.remember_tool_approvals") {
        (sections.ui ||= []).push(`remember_tool_approvals = ${formatted}`);
      } else if (f.id === "permissions.default_selected_permission") {
        (sections.ui ||= []).push(`default_selected_permission = ${formatted}`);
      } else {
        (sections[sec] ||= []).push(`${key} = ${formatted}`);
      }
    } else if (f.id !== "provider.id" && f.id !== "model.custom.id" && f.id !== "mcp.id") {
      topLines.push(`${f.path} = ${formatted}`);
    }
  }

  const header = [
    `# Generated Titanium config · ${product || "agent"}`,
    `# Merge into ${schema.configPath || "config"}`,
    `# Generated: ${new Date().toISOString()}`,
    "",
  ].join("\n");

  let out = header + (topLines.length ? topLines.join("\n") + "\n\n" : "\n");

  const preferredOrder = [
    "cli",
    "marketplace",
    "models",
    "endpoints",
    "sandbox",
    "permissions",
    "session",
    "hints",
    "ui",
    "tools",
    "features",
    "memory",
    "subagents",
    "subagents.toggle",
    "skills",
    "harness",
    "telemetry",
    "auth",
    "plugins",
  ];
  const seen = new Set<string>();
  for (const sec of preferredOrder) {
    if (!sections[sec]) continue;
    seen.add(sec);
    out += `[${sec}]\n${sections[sec]!.join("\n")}\n\n`;
  }
  for (const [sec, lines] of Object.entries(sections)) {
    if (seen.has(sec)) continue;
    out += `[${sec}]\n${lines.join("\n")}\n\n`;
  }

  if (product === "grok") {
    const mkt: { name: string; git: string }[] = [];
    if (enabled.has("marketplace.source.xai") && values["marketplace.source.xai"]) {
      mkt.push({ name: "xAI Official", git: String(values["marketplace.source.xai"]) });
    }
    if (enabled.has("marketplace.source.grok_marketplace") && values["marketplace.source.grok_marketplace"]) {
      mkt.push({ name: "grok-marketplace", git: String(values["marketplace.source.grok_marketplace"]) });
    }
    if (enabled.has("marketplace.source.ds4cc") && values["marketplace.source.ds4cc"]) {
      mkt.push({ name: "ds4cc-marketplace", git: String(values["marketplace.source.ds4cc"]) });
    }
    for (const m of mkt) {
      out += `[[marketplace.sources]]\nname = ${JSON.stringify(m.name)}\ngit = ${JSON.stringify(m.git)}\n\n`;
    }
  }

  if (product === "codex") {
    out += "[profiles.titanium]\n";
    if (enabled.has("model") && values.model) out += `model = ${JSON.stringify(String(values.model))}\n`;
    if (enabled.has("approval_policy") && values.approval_policy)
      out += `approval_policy = ${JSON.stringify(String(values.approval_policy))}\n`;
    if (enabled.has("sandbox_mode") && values.sandbox_mode)
      out += `sandbox_mode = ${JSON.stringify(String(values.sandbox_mode))}\n`;
    out += "\n";
  }

  return out;
}

function generateEnv(schema: ProductSchema, enabled: Set<string>, values: Values): string {
  const lines = [
    `# Environment overrides · ${schema.productTitle || schema.product}`,
    `# Generated: ${new Date().toISOString()}`,
    "",
  ];
  let count = 0;
  for (const f of schema.fields) {
    if (!enabled.has(f.id) || !f.env) continue;
    const raw = values[f.id];
    if (raw == null || raw === "") continue;
    if (f.env === "GROK_DISABLE_AUTOUPDATER") {
      if (raw === false) {
        lines.push("export GROK_DISABLE_AUTOUPDATER=1");
        count++;
      }
      continue;
    }
    let val: string;
    if (typeof raw === "boolean") val = raw ? "1" : "0";
    else if (typeof raw === "number") val = String(raw);
    else if (Array.isArray(raw)) val = raw.join(",");
    else val = String(raw);
    lines.push(`export ${f.env}=${JSON.stringify(val)}`);
    count++;
  }
  if (!count) lines.push("# (no env-mapped settings enabled)");
  lines.push("");
  return lines.join("\n");
}

function generateCli(schema: ProductSchema, enabled: Set<string>, values: Values): string {
  const product = schema.product || "";
  if (product === "codex") {
    return [
      "# Codex Titanium launch",
      `# Generated: ${new Date().toISOString()}`,
      "",
      "codex --profile titanium",
      "",
      '# Headless: codex --profile titanium exec "your prompt"',
      "",
    ].join("\n");
  }
  if (product === "opencode") {
    return [
      "# OpenCode Titanium launch",
      `# Generated: ${new Date().toISOString()}`,
      "",
      "opencode",
      "",
      "# Ensure opencode.json is in the project root or ~/.config/opencode/",
      "",
    ].join("\n");
  }

  const parts = ["grok"];
  if (enabled.has("models.default") && values["models.default"]) {
    parts.push(`-m ${values["models.default"]}`);
  }
  if (enabled.has("models.default_reasoning_effort") && values["models.default_reasoning_effort"]) {
    parts.push(`--effort ${values["models.default_reasoning_effort"]}`);
  }
  if (enabled.has("sandbox.profile") && values["sandbox.profile"]) {
    parts.push(`--sandbox ${values["sandbox.profile"]}`);
  }
  if (
    enabled.has("permissions.permission_mode") &&
    values["permissions.permission_mode"] === "always-approve"
  ) {
    parts.push("--always-approve");
  }
  if (enabled.has("features.subagents") && values["features.subagents"] === false) {
    parts.push("--no-subagents");
  }
  if (enabled.has("cli.auto_update") && values["cli.auto_update"] === false) {
    parts.push("--no-auto-update");
  }
  const joined = parts.join(" ");
  return [
    "# Example launch flags derived from your selection",
    `# Generated: ${new Date().toISOString()}`,
    "",
    joined,
    "",
    "# Headless one-shot:",
    `${joined} -p "your prompt" --output-format streaming-json`,
    "",
  ].join("\n");
}

function generateMarkdown(schema: ProductSchema, config: string, env: string, cli: string): string {
  const title = schema.productTitle || schema.product || "Config";
  const flags = (schema.cliFlags || [])
    .map((f) => `| \`${f.flag}\` | ${f.category} | ${f.description} |`)
    .join("\n");
  const envs = (schema.envVars || [])
    .map((e) => `| \`${e.name}\` | ${e.category} | ${e.description} |`)
    .join("\n");
  const subs = (schema.subcommands || [])
    .map((c) => `- \`${c.cmd}\` — ${c.desc}`)
    .join("\n");

  return [
    `# ${title} — Config Reference`,
    "",
    `> Generated by **Agent Config Builders · Titanium**`,
    "",
    `**Config path:** \`${schema.configPath || ""}\``,
    "",
    schema.productTagline ? `${schema.productTagline}\n` : "",
    "## Your patch",
    "",
    "```",
    config.trimEnd(),
    "```",
    "",
    "## Environment",
    "",
    "```bash",
    env.trimEnd(),
    "```",
    "",
    "## Launch",
    "",
    "```bash",
    cli.trimEnd(),
    "```",
    "",
    subs ? `## Subcommands\n\n${subs}\n` : "",
    flags ? `## Flags\n\n| Flag | Category | Description |\n| --- | --- | --- |\n${flags}\n` : "",
    envs ? `## Environment variables\n\n| Variable | Category | Description |\n| --- | --- | --- |\n${envs}\n` : "",
    schema.product === "grok"
      ? [
          "## xbgst · Titanium host notes",
          "",
          "1. Copy `config.toml` into `~/.grok/config.toml`",
          "2. `grok plugin marketplace add VeigaPunk/grok-marketplace`",
          "3. `grok plugin install xbgst-stack@veigapunk/grok-marketplace --trust`",
          "4. Run the xbgst-stack host install scripts (livepatch-aligned binary)",
          "5. Hard-ban of `general-purpose` / `explore` is enforced by livepatch + `[subagents.toggle]`",
          "",
          "Recommended static file: `/recommended-grok-config.toml`",
          "",
        ].join("\n")
      : "",
    schema.product === "codex"
      ? [
          "## Sekhmet pairing",
          "",
          "Titanium unrestricted is the intended runtime for [Sekhmet / xbrd-spark](https://github.com/VeigaPunk/xbrd-spark).",
          "Use `codex --profile titanium` so concurrent `sekhmet swarm -j N` (cap 64) matches agent wiring.",
          "",
        ].join("\n")
      : "",
  ]
    .filter(Boolean)
    .join("\n");
}

export function generatePatch(
  schema: ProductSchema,
  enabled: Set<string>,
  values: Values,
): GenerateResult {
  const isJson = schema.format === "json";
  const config = isJson
    ? generateJson(schema, enabled, values)
    : generateToml(schema, enabled, values);
  const env = generateEnv(schema, enabled, values);
  const cli = generateCli(schema, enabled, values);
  const markdown = generateMarkdown(schema, config, env, cli);
  return {
    config,
    env,
    cli,
    markdown,
    filename: isJson ? "opencode.json" : "config.toml",
    mime: isJson ? "application/json" : "application/toml",
  };
}

export function defaultValues(schema: ProductSchema): Values {
  const v: Values = {};
  for (const f of schema.fields) {
    if (f.default != null) v[f.id] = f.default;
  }
  const p = schema.presets[0];
  if (p?.values) Object.assign(v, p.values);
  return v;
}

export function applyPreset(
  schema: ProductSchema,
  presetId: string,
  values: Values,
): { enabled: Set<string>; values: Values } {
  const p = schema.presets.find((x) => x.id === presetId);
  if (!p) return { enabled: new Set(), values: { ...values } };
  return {
    enabled: new Set(p.enabled),
    values: { ...values, ...p.values },
  };
}
