import { FIELDS, type ConfigField } from "./schema";

export type BuilderState = {
  enabled: Set<string>;
  values: Record<string, unknown>;
};

function escapeTomlString(s: string): string {
  return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

function formatTomlValue(field: ConfigField, value: unknown): string | null {
  if (value === undefined || value === null || value === "") return null;

  switch (field.type) {
    case "boolean":
      return value ? "true" : "false";
    case "number": {
      const n = Number(value);
      if (Number.isNaN(n)) return null;
      return String(n);
    }
    case "enum":
    case "string":
      return escapeTomlString(String(value));
    case "string-list": {
      const list = Array.isArray(value)
        ? value
        : String(value)
            .split(",")
            .map((x) => x.trim())
            .filter(Boolean);
      if (list.length === 0) return null;
      return `[${list.map((x) => escapeTomlString(String(x))).join(", ")}]`;
    }
    case "map":
      return null;
    default:
      return escapeTomlString(String(value));
  }
}

/** Map field id → TOML section + key (handles model.custom specially) */
function resolveTomlKey(
  field: ConfigField,
  values: Record<string, unknown>,
): { section: string; key: string } | null {
  if (field.id.startsWith("model.custom.")) {
    const modelId = String(values["model.custom.id"] ?? "grok-4.5");
    if (field.id === "model.custom.id") return null;
    const key = field.id.replace("model.custom.", "");
    return { section: `model.${JSON.stringify(modelId)}`, key };
  }

  // permissions keys that aren't real TOML under [permissions] for some —
  // still emit under logical sections
  if (field.path.startsWith("permissions.")) {
    const key = field.path.slice("permissions.".length);
    // permission_mode is common; others may be ui/env only
    if (key === "permission_mode") {
      return { section: "permissions", key: "permission_mode" };
    }
    if (key === "remember_tool_approvals") {
      return { section: "ui", key: "remember_tool_approvals" };
    }
    if (key === "default_selected_permission") {
      return { section: "ui", key: "default_selected_permission" };
    }
  }

  if (field.path.startsWith("features.")) {
    const key = field.path.slice("features.".length);
    if (key === "telemetry") return { section: "features", key: "telemetry" };
    // map feature toggles into sensible TOML when no official key
    return { section: "features", key };
  }

  if (field.path.startsWith("tools.")) {
    return { section: "tools", key: field.path.slice("tools.".length) };
  }

  const parts = field.path.split(".");
  if (parts.length === 2) {
    return { section: parts[0]!, key: parts[1]! };
  }
  if (parts.length === 3) {
    return { section: `${parts[0]}.${parts[1]}`, key: parts[2]! };
  }
  return { section: field.section, key: parts[parts.length - 1]! };
}

export function generateToml(state: BuilderState): string {
  const { enabled, values } = state;
  const sections = new Map<string, string[]>();

  const modelProviderEnabled = [...enabled].some((id) =>
    id.startsWith("model.custom."),
  );

  for (const field of FIELDS) {
    if (!enabled.has(field.id)) continue;
    if (field.id.startsWith("model.custom.") && !modelProviderEnabled) continue;

    const resolved = resolveTomlKey(field, values);
    if (!resolved) continue;

    const formatted = formatTomlValue(field, values[field.id]);
    if (formatted === null) continue;

    const lines = sections.get(resolved.section) ?? [];
    lines.push(`${resolved.key} = ${formatted}`);
    sections.set(resolved.section, lines);
  }

  // Order sections sensibly
  const order = [
    "models",
    "sandbox",
    "permissions",
    "session",
    "cli",
    "hints",
    "ui",
    "tools",
    "features",
    "harness",
    "telemetry",
    "auth",
    "auth.oidc",
    "grok_com_config",
    "plugins",
  ];

  const header = [
    "# Grok Build config patch",
    "# Generated by Grok Build Config Builder",
    "# Merge into ~/.grok/config.toml (or $GROK_HOME/config.toml)",
    `# Generated: ${new Date().toISOString()}`,
    "",
  ];

  const body: string[] = [];
  const seen = new Set<string>();

  for (const sec of order) {
    if (!sections.has(sec)) continue;
    seen.add(sec);
    body.push(`[${sec}]`);
    body.push(...sections.get(sec)!);
    body.push("");
  }

  for (const [sec, lines] of sections) {
    if (seen.has(sec)) continue;
    body.push(`[${sec}]`);
    body.push(...lines);
    body.push("");
  }

  if (body.length === 0) {
    return [
      ...header,
      "# (no settings enabled — toggle fields in the builder)",
      "",
    ].join("\n");
  }

  return [...header, ...body].join("\n");
}

export function generateEnv(state: BuilderState): string {
  const { enabled, values } = state;
  const lines = [
    "# Environment overrides for Grok Build",
    "# Export these in your shell or CI environment",
    `# Generated: ${new Date().toISOString()}`,
    "",
  ];

  for (const field of FIELDS) {
    if (!enabled.has(field.id) || !field.env) continue;
    const raw = values[field.id];
    if (raw === undefined || raw === null || raw === "") continue;

    // Special: GROK_DISABLE_AUTOUPDATER is inverse of auto_update
    if (field.env === "GROK_DISABLE_AUTOUPDATER") {
      if (raw === false) {
        lines.push(`export GROK_DISABLE_AUTOUPDATER=1`);
      }
      continue;
    }

    let val: string;
    if (typeof raw === "boolean") {
      val = raw ? "1" : "0";
    } else {
      val = String(raw);
    }
    lines.push(`export ${field.env}=${JSON.stringify(val)}`);
  }

  if (lines.length === 4) {
    lines.push("# (no env-mapped settings enabled)");
  }

  lines.push("");
  return lines.join("\n");
}

export function generateCliSnippet(state: BuilderState): string {
  const { enabled, values } = state;
  const parts = ["grok"];

  if (enabled.has("models.default") && values["models.default"]) {
    parts.push(`-m ${String(values["models.default"])}`);
  }
  if (
    enabled.has("models.default_reasoning_effort") &&
    values["models.default_reasoning_effort"]
  ) {
    parts.push(`--effort ${String(values["models.default_reasoning_effort"])}`);
  }
  if (enabled.has("sandbox.profile") && values["sandbox.profile"]) {
    parts.push(`--sandbox ${String(values["sandbox.profile"])}`);
  }
  if (
    enabled.has("permissions.permission_mode") &&
    values["permissions.permission_mode"] === "always-approve"
  ) {
    parts.push("--always-approve");
  }
  if (enabled.has("features.memory") && values["features.memory"] === true) {
    parts.push("--experimental-memory");
  }
  if (enabled.has("features.memory") && values["features.memory"] === false) {
    parts.push("--no-memory");
  }
  if (enabled.has("features.subagents") && values["features.subagents"] === false) {
    parts.push("--no-subagents");
  }
  if (enabled.has("cli.auto_update") && values["cli.auto_update"] === false) {
    parts.push("--no-auto-update");
  }

  const lines = [
    "# Example launch flags derived from your selection",
    `# Generated: ${new Date().toISOString()}`,
    "",
    parts.join(" "),
    "",
    "# Headless one-shot example:",
    `${parts.join(" ")} -p "your prompt" --output-format streaming-json`,
    "",
  ];
  return lines.join("\n");
}

export function countEnabled(state: BuilderState): number {
  return state.enabled.size;
}
