import {
  CLI_FLAGS,
  ENV_VARS,
  FIELDS,
  GROUPS,
  SUBCOMMANDS,
} from "./schema";

/** Full reference document compiled from the same schema as the builder */
export function generateFullMarkdown(): string {
  const lines: string[] = [];
  const push = (...xs: string[]) => lines.push(...xs);

  push(
    "# Grok Build CLI — Complete Config Reference",
    "",
    "> Compiled reference for **Grok Build** (`grok`) configuration: CLI flags, `config.toml`, environment variables, layers, sandbox, and permissions.",
    ">",
    "> Latest documented binary track: **v0.2.117** (Jul 30, 2026) · Powered by **Grok 4.5**",
    ">",
    "> Sources: [x.ai/cli](https://x.ai/cli) · [Changelog](https://x.ai/build/changelog) · [CLI reference](https://docs.x.ai/build/cli/reference) · [Settings](https://docs.x.ai/build/settings) · [Settings reference](https://docs.x.ai/build/settings/reference) · [Enterprise](https://docs.x.ai/build/enterprise)",
    "",
    "---",
    "",
    "## Install & version",
    "",
    "```bash",
    "# macOS / Linux",
    "curl -fsSL https://x.ai/cli/install.sh | bash",
    "",
    "# Windows PowerShell",
    "irm https://x.ai/cli/install.ps1 | iex",
    "",
    "grok version",
    "grok update --check",
    "grok update --stable",
    "```",
    "",
    "Requires **SuperGrok** or **X Premium+**. Sign in with `grok login` (or `grok login --device-auth` for headless/SSH).",
    "",
    "Open source harness: [github.com/xai-org/grok-build](https://github.com/xai-org/grok-build) (Apache 2.0).",
    "",
    "---",
    "",
    "## Configuration layers",
    "",
    "Grok loads configuration from five layers (lowest → highest priority):",
    "",
    "| Priority | Source | Purpose |",
    "| ---: | --- | --- |",
    "| 1 | `/etc/grok/managed_config.toml` | System-wide managed defaults |",
    "| 2 | `~/.grok/managed_config.toml` | Per-user managed defaults |",
    "| 3 | `~/.grok/config.toml` (`$GROK_HOME/config.toml`) | User preferences |",
    "| 4 | `~/.grok/requirements.toml` | User-level pinned settings |",
    "| 5 | `/etc/grok/requirements.toml` | System pins (highest, fail-closed) |",
    "",
    "**Project** `.grok/config.toml` may only contribute MCP servers, plugins, and permission rules — not full user UI prefs.",
    "",
    "All layers support `[[version_overrides]]` and `$VAR` expansion. Values in `requirements.toml` cannot be overridden by lower layers, remote settings, or user config.",
    "",
    "Confirm loaded config with:",
    "",
    "```bash",
    "grok inspect",
    "grok inspect --json",
    "```",
    "",
    "---",
    "",
    "## Subcommands",
    "",
    "| Command | Description |",
    "| --- | --- |",
  );

  for (const s of SUBCOMMANDS) {
    push(`| \`${s.cmd}\` | ${s.desc} |`);
  }

  push(
    "",
    "Running `grok` with no arguments starts the interactive TUI.",
    "",
    "---",
    "",
    "## Session launch flags",
    "",
    "| Flag | Category | Description |",
    "| --- | --- | --- |",
  );

  for (const f of CLI_FLAGS) {
    push(`| \`${f.flag}\` | ${f.category} | ${f.description} |`);
  }

  push(
    "",
    "### Claude Code aliases",
    "",
    "| Alias | Maps to |",
    "| --- | --- |",
    "| `--allowedTools` | `--tools` |",
    "| `--disallowedTools` | `--disallowed-tools` |",
    "| `--append-system-prompt` | `--rules` |",
    "| `--system-prompt` | `--system-prompt-override` |",
    "| `--dangerously-skip-permissions` | `--always-approve` |",
    "",
    "---",
    "",
    "## Sandbox profiles",
    "",
    "| Profile | Read | Write | Network (Linux) | Use |",
    "| --- | --- | --- | --- | --- |",
    "| `off` | unrestricted | unrestricted | allowed | Default |",
    "| `workspace` | everywhere | CWD + `~/.grok/temp` | allowed | Normal development |",
    "| `devbox` | everywhere | top-level dirs except `/data` | allowed | Cloud devbox |",
    "| `read-only` | everywhere | `~/.grok/temp` | blocked | Code review |",
    "| `strict` | CWD/system | CWD + temp | blocked | Untrusted repos |",
    "",
    "Enable via CLI `--sandbox workspace`, config `[sandbox] profile = \"workspace\"`, or env `GROK_SANDBOX=workspace`.",
    "",
    "Custom profiles live in `~/.grok/sandbox.toml` or `.grok/sandbox.toml`:",
    "",
    "```toml",
    "[profiles.my-profile]",
    'extends = "workspace"',
    "restrict_network = true",
    'deny = ["/secrets", "**/.env", "**/*.pem"]',
    "```",
    "",
    "---",
    "",
    "## Permissions",
    "",
    "- `permission_mode`: `auto` (default) | `ask` | `always-approve`",
    "- Legacy keys: `approval_mode`, `yolo = true`",
    "",
    "```toml",
    "rules = [",
    '  { action = "allow", tool = "bash", pattern = "git *" },',
    '  { action = "allow", tool = "read" },',
    '  { action = "deny",  tool = "bash", pattern = "rm -rf *" },',
    "]",
    "```",
    "",
    "CLI: `--allow '<pattern>'` / `--deny '<pattern>'`. Tools: `Bash`, `Edit`, `Read`, `Grep`, `MCPTool`, `WebFetch`, `WebSearch`. **Deny always overrides allow.**",
    "",
    "---",
    "",
    "## config.toml settings",
    "",
  );

  for (const group of GROUPS) {
    push(`### ${group.title}`, "", group.description, "");
    const fields = FIELDS.filter((f) => f.group === group.id);
    if (fields.length === 0) continue;
    push("| Key | Type | Default | Env | CLI | Description |", "| --- | --- | --- | --- | --- | --- |");
    for (const f of fields) {
      push(
        `| \`${f.path}\` | ${f.type}${f.options ? ` (${f.options.join(" \\| ")})` : ""} | ${f.default !== undefined ? `\`${String(f.default)}\`` : "—"} | ${f.env ? `\`${f.env}\`` : "—"} | ${f.cli ? `\`${f.cli}\`` : "—"} | ${f.description} |`,
      );
    }
    push("");
  }

  push(
    "### Starter sample",
    "",
    "```toml",
    "[models]",
    'default = "grok-build"',
    'web_search = "grok-4.5"',
    "",
    '[model."grok-4.5"]',
    'model = "grok-4.5"',
    'base_url = "https://api.x.ai/v1"',
    'name = "Grok 4.5"',
    'env_key = "XAI_API_KEY"',
    'api_backend = "responses"',
    "temperature = 0.7",
    "top_p = 0.95",
    "max_completion_tokens = 8192",
    "context_window = 1000000",
    "supports_backend_search = true",
    "",
    "[sandbox]",
    'profile = "workspace"',
    "auto_allow_bash = false",
    "",
    "[cli]",
    "auto_update = true",
    'channel = "stable"',
    "",
    "[ui]",
    'theme = "auto"',
    "show_thinking_blocks = true",
    'screen_mode = "fullscreen"',
    "",
    "[harness]",
    "disable_codebase_upload = true",
    "",
    "[telemetry]",
    "trace_upload = false",
    "",
    "[features]",
    "telemetry = false",
    "",
    "[mcp_servers.filesystem]",
    'command = "npx"',
    'args = ["-y", "@modelcontextprotocol/server-filesystem", "/path/to/allowed"]',
    "enabled = true",
    "startup_timeout_sec = 30",
    "tool_timeout_sec = 6000",
    "```",
    "",
    "---",
    "",
    "## Environment variables",
    "",
    "| Variable | Category | Description |",
    "| --- | --- | --- |",
  );

  for (const e of ENV_VARS) {
    push(`| \`${e.name}\` | ${e.category} | ${e.description} |`);
  }

  push(
    "",
    "---",
    "",
    "## Privacy notes",
    "",
    "- Client config keys: `[harness] disable_codebase_upload`, `[telemetry] trace_upload`, `[features] telemetry`.",
    "- xAI also applies **server-side** controls for codebase upload; keep client flags set anyway.",
    "- Use `/privacy` in the TUI for account privacy options.",
    "- Team **Zero Data Retention (ZDR)** is an enterprise control (see enterprise docs).",
    "",
    "---",
    "",
    "## Headless examples",
    "",
    "```bash",
    'grok -p "summarize this repo" --output-format json --always-approve',
    'grok -p "fix types" --output-format streaming-json --sandbox workspace --no-auto-update',
    "```",
    "",
    "---",
    "",
    "## Useful links",
    "",
    "- Product: https://x.ai/cli",
    "- Changelog: https://x.ai/build/changelog",
    "- CLI reference: https://docs.x.ai/build/cli/reference",
    "- Settings: https://docs.x.ai/build/settings",
    "- Settings reference: https://docs.x.ai/build/settings/reference",
    "- Headless: https://docs.x.ai/build/cli/headless-scripting",
    "- Enterprise: https://docs.x.ai/build/enterprise",
    "- Source: https://github.com/xai-org/grok-build",
    "",
  );

  return lines.join("\n");
}
